version: '3.3'
services:
  consul:
    image: consul:${CONSUL_VERSION}
    container_name: consul
    command: >-
      agent
      -bind=0.0.0.0
      -config-file=/config.json
    volumes:
      - ./config/consul.json:/config.json
    networks:
      - vault
    ports:
      - "9300:9300"
      - "9500:9500"
      - "9600:9600/udp"

  vault:
    image: vault:${VAULT_VERSION}
    container_name: vault
    ports:
      - "8200:8200"
    volumes:
      - ./config/vault.json:/config.json
    cap_add:
      - IPC_LOCK
    networks:
      - vault
    command: >-
      server
      -config=/config.json

  vaultui:
    container_name: vaultui
    image: djenriquez/vault-ui
    ports:
      - "8000:8000"
    links:
      - vault:vault
    networks:
      - vault
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - VAULT_ADDR=http://vault:8200

  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CONSUL_HTTP_ADDR=consul:9500
      - VAULT_ADDR=http://vault:8200
    volumes:
      - ./client-scripts:/mnt/data
    networks:
      - vault
    command: tail -f /dev/null

networks:
  vault:
